### ISSUE TITLE
Very minor documentation issue (`dotify()` export)

### ISSUE THREAD

**Issue by francisbarton** [kevinushey/dotty#1]
Hi Kevin,
Thanks for making this package.

Just to note that your README says:

```
.onLoad <- function(libname, pkgname) {
  dotty::dotify()
}
```

but `dotify()` is currently not `@export`ed so I think this needs to be `dotty:::dotify()` in the README instructions.

**Comment by kevinushey** [comment]
Thanks! I'll get this fixed up.

**Comment by kevinushey** [comment]
Now exported in https://github.com/kevinushey/dotty/commit/56c8a4ff9a67f9eafc85ca17b7cc7bd63ecbb9a3 -- thanks!
